name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Lua 5.3
        uses: leafo/gh-actions-lua@v10
        with:
          lua-version: "5.3"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install tooling
        run: |
          luarocks install luacheck
          luarocks install busted

      - name: Lint
        run: ./tools/lint.sh

      - name: Tests
        run: ./tools/test.sh

      - name: Asset audit
        run: ./tools/check_assets.sh
